name: Git Workflows

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Packer-Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Connect to PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'postgres'
          postgresql user: 'postgres'
          postgresql password: 'test@123'
      - name: Build with Maven
        working-directory: demo
        run: mvn clean install
      - name: Running test cases
        working-directory: demo
        run: mvn test -Dtest=HealthCheckTests
      - name: Building Jar file
        working-directory: demo
        run: mvn package -Dmaven.test.skip=true
      - name: Checking AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Installing packer provisioners
        working-directory: packer_tmp
        run: packer init aws-debian.pkr.hcl
      - name: Formatting Packer file
        working-directory: packer_tmp
        run: packer fmt -check aws-debian.pkr.hcl
      - name: Validating Packer file
        working-directory: packer_tmp
        run: packer validate aws-debian.pkr.hcl
